import type { Metadata } from 'next'
import { LayoutApp } from '@/components/LayoutApp'
import { Sidebar } from '@/components/Sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <div className='grid min-h-screen grid-cols-app data-[open="true"]:grid-cols-closedSidebar data-[open="true"]:bg-red-500'>
          <Sidebar/>
          <main className="px-4 pb-12 pt-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
